name: Build-SDK
on: [workflow_dispatch, pull_request]

jobs:
  build-linux-arm:
    name: Build sd.cpp for Linux arm64
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Repositories
        run: sudo mv crosscomp-sources.lst /etc/apt/sources.list;
      - name: Check apt sources
        run: cat /etc/apt/sources.list
      - name: Add arm64 as architecture
        run: sudo dpkg --add-architecture arm64
      - name: Update APT
        run:  sudo apt update && exit 0;
      - name: Install Host Dependencies
        run: sudo apt install cmake:amd64 ninja-build:amd64 gcc-12-aarch64-linux-gnu:amd64 g++-12-aarch64-linux-gnu:amd64 bison:amd64 python3-distutils:amd64 ocaml-core:amd64 xz-utils:amd64 pkg-config:amd64
      - name: Install Target Dependencies
        run: | 
          sudo apt install libvulkan-dev:arm64 glslc -y --no-install-recommends
      - name: Download
        run: git clone https://github.com/leejet/stable-diffusion.cpp
      - name: Build
        run: |
          export CMAKE_TOOLCHAIN_FILE=`pwd`/aarch64-toolchain.cmake
          mkdir stable-diffuison.cpp/build
          cd stable-diffuison.cpp/build
          cmake .. -DCMAKE_TOOLCHAIN_FILE=`pwd`/aarch64-toolchain.cmake -DSD_VULKAN=ON
          cmake --build . --config Release
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name:  sd.cpp-arm
          path:  stable-diffusion.cpp/build/bin/
          
          
